# Application
spring.application.name=screensound
spring.config.import=optional:file:.env[.properties]
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
# Database
app.database.host=${DB_HOST:localhost}
app.database.port=${DB_PORT:5432}
app.database.name=${DB_NAME}
app.database.username=${DB_USERNAME}
app.database.password=${DB_PASSWORD}
# DataSource
spring.datasource.url=jdbc:postgresql://${app.database.host}:${app.database.port}/${app.database.name}
spring.datasource.username=${app.database.username}
spring.datasource.password=${app.database.password}
